name: BedWars1058-GroupStats
version: '${project.version}'
main: me.infinity.groupstats.GroupStatsPlugin
softdepend: [ BedWars1058 ]
authors: [ I6y ]
description: Addon for bedwars1058, for getting arena group statistics of player.
